name: "Connor Letko - Portfolio"
description: "Portfolio For Use"
google: "UA-153630802-1"
url: 'https://cjl72.github.io/mini3/'
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
paginate: 10
paginate_path: /page-:num

#disqus-id: your-disqus-id

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: assets/css/

